### ISSUE TITLE
Leaky bucket updates the key when reading

### ISSUE THREAD

**Issue by grosser** [zendesk/prop#9]
This seems unnecessary ... @shanitang can you fix that ?

**Comment by shanitang** [comment]
@grosser Do you mean the `counter` method updates the key when it's called?

**Comment by grosser** [comment]
yes

**Comment by shanitang** [comment]
https://github.com/zendesk/prop/blob/master/lib/prop/limiter.rb#L120-L130 We use `@strategy.conter` in limiter to return the current hits, and that's why it updates the key when counter is called. Does it make sense?

**Comment by grosser** [comment]
it does not make sense to me to write/update the counter when I want to know what the current count is ... that should just be a read ...

**Comment by shanitang** [comment]
Does that mean we should just read the current count and return it even if the number is not the real count for the moment?

**Comment by grosser** [comment]
read it, calculate the real number and return that ?

**Comment by shanitang** [comment]
ok! I'll update it! Thanks @grosser

**Comment by grosser** [comment]
thx! :D

**Comment by grosser** [comment]
fixed in https://github.com/zendesk/prop/pull/7
